"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { collection, getDocs, limit, orderBy, query, QueryConstraint, QueryDocumentSnapshot, DocumentData, startAfter, where } from "firebase/firestore";
import { useRouter } from "next/navigation";
import { Heart } from "lucide-react";
import { db } from "@/lib/firebase.config";
import { useCart } from "@/hook/useAddToCart";
import { useWishlist } from "@/hook/useAddToWishList";

interface Product { id: string; name: string; price: number; imageUrls: string[]; category: string; subCategory?: string; badge?: string; stock?: number; }
const PLACEHOLDER_IMAGE = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='800' height='1000' viewBox='0 0 800 1000'%3E%3Crect width='800' height='1000' fill='%23e5e8e0'/%3E%3Cpath d='M160 760 340 540l120 150 90-110 150 180' fill='none' stroke='%2392a59a' stroke-width='18'/%3E%3Ccircle cx='290' cy='315' r='48' fill='none' stroke='%2392a59a' stroke-width='18'/%3E%3C/svg%3E";
const PAGE_SIZE = 10;
const formatPrice = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);

function ProductCard({ product, wishlisted, wishlistBusy, onToggleWishlist, onQuickAdd, addBusy }: { product: Product; wishlisted: boolean; wishlistBusy: boolean; onToggleWishlist: () => void; onQuickAdd: () => void; addBusy: boolean; }) {
  const router = useRouter();
  const soldOut = product.stock === 0;
  const coverImage = product.imageUrls?.[0] ?? PLACEHOLDER_IMAGE;
  return <div className="group w-full cursor-pointer" onClick={() => router.push(`/${product.id}`)}>
    <div className="relative mb-3 aspect-[0.78] w-full overflow-hidden rounded-[1.25rem] bg-warm-gray sm:mb-4">
      <img src={coverImage} alt={product.name} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105" />
      {product.badge && <div className="absolute left-3 top-3"><span className="bg-[#0f473a] px-2.5 py-1 text-[9px] font-bold uppercase tracking-widest text-white">{product.badge}</span></div>}
      <button onClick={(event) => { event.stopPropagation(); onToggleWishlist(); }} disabled={wishlistBusy} className="absolute right-3 top-3 flex h-8 w-8 items-center justify-center rounded-full bg-white/90 shadow-sm transition-opacity hover:scale-110 disabled:opacity-50 sm:opacity-0 sm:group-hover:opacity-100" aria-label="Add to wishlist"><Heart size={15} strokeWidth={1.7} className={wishlisted ? "fill-[#b55f4c] text-[#b55f4c]" : "text-[#55766a]"} /></button>
      <div className="absolute inset-x-0 bottom-0 translate-y-full transition-transform duration-300 group-hover:translate-y-0"><button onClick={(event) => { event.stopPropagation(); onQuickAdd(); }} disabled={soldOut || addBusy} className="w-full bg-[#0f473a] py-3 text-[10px] font-semibold uppercase tracking-[0.13em] text-white transition-colors hover:bg-[#1e6151] disabled:cursor-not-allowed disabled:opacity-50">{soldOut ? "Sold out" : addBusy ? "Adding..." : "Quick add"}</button></div>
    </div>
    <p className="mb-1 text-[9px] font-semibold uppercase tracking-widest text-[#728178] sm:text-[10px]">{product.subCategory ?? product.category}</p><h3 className="truncate text-xs font-medium text-[#173f35] transition-colors group-hover:text-[#5d8a7b] sm:text-sm">{product.name}</h3><p className="mt-1 text-xs font-semibold text-[#173f35] sm:text-sm">{formatPrice(product.price)}</p>
  </div>;
}

function SkeletonCard() { return <div className="w-full animate-pulse"><div className="mb-3 aspect-[0.78] w-full rounded-[1.25rem] bg-[#e5e8e0] sm:mb-4" /><div className="mb-2 h-2.5 w-20 rounded bg-[#e5e8e0]" /><div className="mb-2 h-3.5 w-4/5 rounded bg-[#e5e8e0]" /><div className="h-3.5 w-1/3 rounded bg-[#e5e8e0]" /></div>; }

export default function PopularProducts() {
  const [products, setProducts] = useState<Product[]>([]); const [loading, setLoading] = useState(true); const [loadingMore, setLoadingMore] = useState(false); const [activeTab, setActiveTab] = useState("All"); const [allCategories, setAllCategories] = useState<string[]>([]); const [lastDoc, setLastDoc] = useState<QueryDocumentSnapshot<DocumentData> | null>(null); const [hasMore, setHasMore] = useState(true); const sentinelRef = useRef<HTMLDivElement | null>(null); const fetchingRef = useRef(false);
  const { addToCart, isAdding } = useCart(); const { isWishlisted, toggleWishlist, isMutating } = useWishlist();
  useEffect(() => { getDocs(collection(db, "products")).then((snap) => setAllCategories(Array.from(new Set(snap.docs.map((doc) => (doc.data() as Product).category).filter(Boolean))))).catch((error) => console.error("Failed to load product categories:", error)); }, []);
  const fetchBatch = useCallback(async (tab: string, cursor: QueryDocumentSnapshot<DocumentData> | null) => { const constraints: QueryConstraint[] = []; if (tab !== "All") constraints.push(where("category", "==", tab)); constraints.push(orderBy("createdAt", "desc")); if (cursor) constraints.push(startAfter(cursor)); constraints.push(limit(PAGE_SIZE)); const snapshot = await getDocs(query(collection(db, "products"), ...constraints)); return { items: snapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() })) as Product[], newLastDoc: snapshot.docs[snapshot.docs.length - 1] ?? null, more: snapshot.docs.length === PAGE_SIZE }; }, []);
  useEffect(() => { let cancelled = false; setLoading(true); setProducts([]); setLastDoc(null); setHasMore(true); fetchBatch(activeTab, null).then(({ items, newLastDoc, more }) => { if (!cancelled) { setProducts(items); setLastDoc(newLastDoc); setHasMore(more); } }).catch((error) => console.error("Failed to load products:", error)).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [activeTab, fetchBatch]);
  const loadMore = useCallback(async () => { if (fetchingRef.current || !hasMore || loading) return; fetchingRef.current = true; setLoadingMore(true); try { const { items, newLastDoc, more } = await fetchBatch(activeTab, lastDoc); setProducts((current) => [...current, ...items]); setLastDoc(newLastDoc); setHasMore(more); } catch (error) { console.error("Failed to load more products:", error); } finally { fetchingRef.current = false; setLoadingMore(false); } }, [activeTab, fetchBatch, hasMore, lastDoc, loading]);
  useEffect(() => { const node = sentinelRef.current; if (!node) return; const observer = new IntersectionObserver((entries) => { if (entries[0].isIntersecting) loadMore(); }, { rootMargin: "400px" }); observer.observe(node); return () => observer.disconnect(); }, [loadMore]);
  const categories = ["All", ...allCategories];
  return <section id="trending" className="border-t border-[#d9ded3] py-16 sm:py-20 lg:py-28"><div className="mb-8 flex flex-col gap-5 sm:mb-10 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Selected for you</p><h2 className="display-title mt-3">Trending pieces.</h2></div>{!loading && categories.length > 1 && <div className="flex items-center gap-2 overflow-x-auto px-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{categories.map((tab) => <button key={tab} onClick={() => setActiveTab(tab)} className={`flex-shrink-0 whitespace-nowrap rounded-full px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[0.1em] transition-all sm:px-4 ${activeTab === tab ? "bg-[#0f473a] text-white" : "border border-[#bdc9bf] text-[#527164] hover:border-[#0f473a] hover:text-[#0f473a]"}`}>{tab}</button>)}</div>}</div>{loading ? <div className="grid grid-cols-2 gap-3 sm:gap-5 md:grid-cols-3 lg:grid-cols-4">{Array.from({ length: 4 }).map((_, index) => <SkeletonCard key={index} />)}</div> : products.length > 0 ? <><div className="grid grid-cols-2 gap-3 sm:gap-5 md:grid-cols-3 lg:grid-cols-4">{products.map((product) => <ProductCard key={product.id} product={product} wishlisted={isWishlisted(product.id)} wishlistBusy={isMutating(product.id)} addBusy={isAdding(product.id)} onToggleWishlist={() => toggleWishlist({ id: product.id, name: product.name, price: product.price, imageUrl: product.imageUrls?.[0] ?? PLACEHOLDER_IMAGE })} onQuickAdd={() => addToCart({ id: product.id, name: product.name, price: product.price, imageUrl: product.imageUrls?.[0] ?? PLACEHOLDER_IMAGE, stock: product.stock, quantity: 1 })} />)}{loadingMore && Array.from({ length: 4 }).map((_, index) => <SkeletonCard key={`more-${index}`} />)}</div>{hasMore && <div ref={sentinelRef} className="h-1" aria-hidden="true" />}{hasMore && !loadingMore && <div className="mt-8 flex justify-center"><button onClick={loadMore} className="rounded-full border border-[#0f473a] px-6 py-2.5 text-[10px] font-semibold uppercase tracking-[0.13em] text-[#0f473a] transition-colors hover:bg-[#0f473a] hover:text-white">Load more</button></div>}</> : <div className="py-16 text-center text-sm text-[#718077]">No pieces are available in this collection yet.</div>}</section>;
}
